application:
  port: 8001
  host: 127.0.0.1

database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "s123"
  database_name: "newsletter"
  required_ssl: false

email_client:
  base_url: "localhost"
  sender_email: "test@example.com"